### ISSUE TITLE
Gamemodes not working on GROUND BRANCH v1034

### ISSUE THREAD

**Issue by Fabus1184** [gbgmc/ground-branch-game-modes#25]
**Describe the bug**
The maps are completely empty, no enemy AI, no HVT, nothing.
Tried all gamemodes, many different Settings.

**To Reproduce**
Play any of these gamemodes

**Expected behavior**
Work

**Desktop (please complete the following information):**
 - CTE 1034, Build 10865 (Beta branch)

**Comment by Bob-AT** [comment]
v1034 is not supported yet. 
I'll paste here more details that I posted on the Discord:

> # NOTE: v1034 _NOT_ supported yet

> From GROUND BRANCH v1033 to v1034, there are some breaking changes with respect to the Lua API, Mission `.mis` files, and Load  `.kit` files that would be need to be adressed/fixed. After the the fix is  done a full re-test of GBGMC is necessary.

> Since GROUND BRANCH v1034 is still in beta and under active development the porting of GBGMC will happend once GROUND BRANCH v1034 leaves the beta.
> Otherwise we would need to re-test multiple times which would just be to time intensive for me.

> Contributions are welcome, so if someone wants to do it just let us know in the Discord. Otherwise I'll start porting once v1034 leaves the beta.
